export const FETCH_PERSONS = 'FETCH_PERSONS';
export const FETCH_PERSONS_IN_PROGRESS = 'FETCH_PERSONS_IN_PROGRESS';
export const FETCH_PERSONS_FAILED = 'FETCH_PERSONS_FAILED';
export const FETCH_PERSONS_SUCCESS = 'FETCH_PERSONS_SUCCESS';
